# Generated by Django 4.2.4 on 2023-08-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=500)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('duration', models.IntegerField(max_length=100)),
            ],
        ),
    ]
