# Generated by Django 4.2.4 on 2023-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
